# Shell variables
# Generated by 'wal'
wallpaper='/home/bolivar/imgs/walls/the_neon_shallows.png'

# Special
background='#0b1118'
foreground='#a6c1b8'
cursor='#a6c1b8'

# Colors
color0='#0b1118'
color1='#554B41'
color2='#962A30'
color3='#F21B2B'
color4='#DF4D49'
color5='#2EA564'
color6='#F6934A'
color7='#a6c1b8'
color8='#748780'
color9='#554B41'
color10='#962A30'
color11='#F21B2B'
color12='#DF4D49'
color13='#2EA564'
color14='#F6934A'
color15='#a6c1b8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
