--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bolivar/imgs/walls/the_neon_shallows.png"

-- Special
background="#0b1118"
foreground="#a6c1b8"
cursor="#a6c1b8"

-- Colors
color0="#0b1118"
color1="#554B41"
color2="#962A30"
color3="#F21B2B"
color4="#DF4D49"
color5="#2EA564"
color6="#F6934A"
color7="#a6c1b8"
color8="#748780"
color9="#554B41"
color10="#962A30"
color11="#F21B2B"
color12="#DF4D49"
color13="#2EA564"
color14="#F6934A"
color15="#a6c1b8"
