#! /bin/sh
#====================================================#
#  ____                                #             #
# | __ ) ___ _ ____      ___ __ ___    # 2021-07-11  #
# |  _ \/ __| '_ \ \ /\ / / '_ ` _ \   # v0.9.1      #
# | |_) \__ \ |_) \ V  V /| | | | | |  #             #
# |____/|___/ .__/ \_/\_/ |_| |_| |_|  # bw8         #
#           |_|                        #             #
#======================================= STARTING ======================================== 
# Xresources
[[ -f ~/.config/Xresources/Xresources ]] && xrdb -merge -I$HOME ~/.config/Xresources/Xresources

# Env colors
[[ -f ~/.config/colors/colors.sh ]] && source "${HOME}/.config/colors/colors.sh"

# Wallpaper
feh --no-fehbg --bg-fill "$wallpaper"

# Sxhkd
pgrep -x sxhkd > /dev/null || \
sxhkd &

# Picom compositor
pgrep -x picom > /dev/null || \
picom -b

# Dunst notifications
pgrep -x dunst > /dev/null || \
dunst &

# Polybar launch script
polybar-start &

#======================================== CONFIG =========================================
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width                3
bspc config window_gap                  20

bspc config top_padding                 23
bspc config bottom_padding              0

bspc config normal_border_color	        "$color4"
bspc config active_border_color	        "$color2"   # focused window of unfocused monitor
bspc config focused_border_color        "$color10"
bspc config presel_feedback_color       "$color3"

bspc config automatic_scheme            longest_side
bspc config initial_polarity            second_child
bspc config directional_focus_tightness high

bspc config presel_feedback             true
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config top_monocle_padding         0
bspc config bottom_monocle_padding      0

bspc config single_monocle              true

bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_corner

bspc config click_to_focus              true
bspc config swallow_first_click         false
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       true

#bspc config ignore_ewmh_focus           true
#bspc config ignore_ewmh_fullscreen      enter

bspc config center_pseudo_tiled         true

bspc config split_ratio                 0.50
bspc config focus_by_distance           true
bspc config history_aware_focus         true

#======================================== RULES ==========================================

bspc rule -a Alacritty:\*			    state=pseudo_tiled      follow=on
bspc rule -a Alacritty:float			    state=floating

bspc rule -a firefox:\*				    state=floating
bspc rule -a firefox:Navigator	    desktop='^2'    state=tiled
bspc rule -a firefox:Toolkit                        state=pseudo_tiled

bspc rule -a VSCodium               desktop='^3'    state=tiled             follow=on
bspc rule -a Zathura                                state=tiled             follow=on

bspc rule -a Thunderbird:Mail       desktop='^6'    state=tiled
bspc rule -a tutanota-desktop       desktop='^6'    state=pseudo_tiled

bspc rule -a qBittorrent	    desktop='^7'	  
bspc rule -a VirtualBoxVM:\*        desktop='^8'    state=pseudo_tiled      rectangle=1500x974+210+56
bspc rule -a VirtualBox\ Manager:\*                 state=pseudo_tiled

bspc rule -a Tor\ Browser:Navigator desktop='^8'    state=pseudo_tiled      rectangle=1500x974+210+56
bspc rule -a Tor\ Browser:\*                        state=floating

bspc rule -a Signal		    desktop='^9'    state=pseudo_tiled      follow=on
bspc rule -a TelegramDesktop	    desktop='^9'    state=pseudo_tiled      follow=on
bspc rule -a discord:discord        desktop='^9'    state=pseudo_tiled      follow=on

bspc rule -a \*:music		    desktop='^10'   state=pseudo_tiled      
bspc rule -a Alacritty:spt	    desktop='^10'   state=pseudo_tiled      follow=on
bspc rule -a Alacritty:cmus	    desktop='^10'   state=pseudo_tiled      follow=on

bspc rule -a mpv				    state=pseudo_tiled
bspc rule -a feh				    state=floating
bspc rule -a Sxiv				    state=pseudo_tiled


#====================================== AUTOSTART ========================================

# Redshift
pgrep -x redshift > /dev/null || \
redshift -c ~/.config/redshift/redshift.conf &

# Emojis and unicode ☢️
pgrep -x ibus-daemon > /dev/null || \
ibus-daemon -drx

#=========================================================================================
